### ISSUE TITLE
Sample project fails to LoadTexture for box.png/ground.png on CLion + Mac using cmake

### ISSUE THREAD

**Issue by andrewfunston** [erincatto/box2d-raylib#3]
A small issue, but might halt someone who's not familiar. Opening, building, and launching work, but - by default - clion when opening a cmake project creates the build folder out of source 

<img width="729" alt="Screenshot 2024-08-23 at 10 22 10 AM" src="https://github.com/user-attachments/assets/61387e73-f21f-48d0-92e3-65a19948b854">

Maybe a quick change to something like this sample project? It's worked on all platforms and IDEs for me so far. Thanks for including the sample project - it's very helpful!

https://github.com/tupini07/raylib-cpp-cmake-template/blob/main/CMakeLists.txt#L88

https://github.com/tupini07/raylib-cpp-cmake-template/blob/main/sources/Constants.hpp#L24

The issue:
<img width="1227" alt="Screenshot 2024-08-23 at 10 26 04 AM" src="https://github.com/user-attachments/assets/9fbf5a43-6df8-419f-8115-6d05fab7f4db">

**Comment by Peter0x44** [comment]
Does CLion not have a way to change the working directory upon running?
I don't think there is much that can be done from the side of this project. Perhaps:
https://cmake.org/cmake/help/latest/prop_tgt/VS_DEBUGGER_WORKING_DIRECTORY.html
But that might not help for CLion.

**Comment by andrewfunston** [comment]
I have sample code links to what works on CLion on mac and everywhere else above for the cmake config. Setting up cmake to build in source is a bad idea even if you're not using CLion.

**Comment by andrewfunston** [comment]
i.e. this project only works if the binary is built in or moved to the source directory OR the assets are copied to where the binary lives - that's not good practice anywhere, but I'm not here to beat that point to death. I just opened this issue to help someone who's unfamiliar with CMake avoid this random pitfall. I'll close the issue.

**Comment by Peter0x44** [comment]
> i.e. this project only works if the binary is built in or moved to the source directory OR the assets are copied to where the binary lives

This is actually irrelevant, what matters is the working directory at runtime. I don't know how to change it in CLion, but I know visual studio and gdb both can. If you just set the working directory to the source directory, no copying is needed.

**Comment by andrewfunston** [comment]
If the CMake config is failing to build a binary that can run out of the box you have a misconfigured or incomplete cmake setup. This is the only CMake project that the samples fails to run that I've played with in a good while. Hence the issue, but again - not a big deal.

**Comment by Peter0x44** [comment]
You can run the binary. It just can't find the resources, because the working directory is not what it expects. Your solution just effectively hardcodes an absolute path that you can then access them from, it is valid, but it's not always what is desired.

**Comment by hbaklan943** [comment]
#### Setting the Working Directory in Clion

1. Go to **Run | Edit Configurations** in CLion.
2. Select your configuration (e.g., `game`).
3. Look for the **Working directory** field.
4. Change it to the directory containing the resource files (e.g., the project folder where `CMakeLists.txt` resides).
