### ISSUE TITLE
Application crash when use precompiled .lib with "AVX2" optimization.

### ISSUE THREAD

**Issue by GitLordv** [erincatto/box2d-raylib#4]
It seems on legacy processors. box2d in pre-compiled .lib library format with "**Advanced Vector Extensions 2 (AVX2)**" optimization, 
causes “Illegal Instruction” exception, and application freeze/crash.

This mostly happens when physical bodies collide, before the first collision everything works.

**Comment by Peter0x44** [comment]
There is no pre compiled lib located here. And yes, you should compile box2d without AVX2 if your CPU doesn't support those instructions. I'm not sure what the problem is.

**Comment by erincatto** [comment]
Box2D should no longer use AVX2 by default. SSE2 is the default.
